function generateIcebreaker() {
  const questions = [
    "What's your favorite way to unwind after a long day of coding?",
    "What hobby would you get into if time and money weren't an issue?",
    "What's the last book you read or movie you watched that you really enjoyed?",
    "If you could visit any country in the world, where would you go and why?",
    "What's one skill you'd like to develop or hobby you'd like to take up?",
    "What's the most memorable vacation you've ever had?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's your favorite season of the year and why?",
    "What’s your favorite dish to cook or eat?",
    "If you could instantly become an expert in something, what would it be?",
    "What's one book you think everyone should read?",
    "What's a skill you learned when you were younger that you still use today?",
    "What’s the most interesting documentary you've ever seen?",
    "If you had to choose only one app on your phone, which one would it be?",
    "What’s your go-to karaoke song?",
    "If you could be any animal for a day, which one would you be and why?",
    "What's your favorite memory from childhood?",
    "What's something you've done that you're really proud of?",
    "What's one goal you have for the next year?",
    "What's a piece of advice you've received that has stuck with you?",
    "What fictional character do you wish you could meet in real life?",
    "What’s one city you’ve visited that surprised you the most?",
    "What’s your favorite way to spend a weekend?",
    "What's the best concert or live event you’ve ever attended?",
    "What’s one language you wish you could speak fluently?",
    "What’s the best gift you’ve ever received?",
    "What’s the last thing you created?",
    "What’s your favorite quote or saying?",
    "What’s one thing you’re excited about that’s coming up in 2023?",
    "If you could master one musical instrument, what would it be?",
    "What’s the funniest thing that happened to you recently?",
    "What’s your favorite tradition or holiday?",
    "If you could switch lives with one person for a day, who would it be?",
    "What’s something you used to do as a child that you miss?",
    "What’s the most daring experience you’ve ever had?",
    "If you could learn any skill in an instant, what would it be?",
    "What's something you've always wanted to try but haven't yet?",
    "What’s your favorite board game or card game?",
    "Who’s someone you really admire?",
    "What’s a common misconception about your job or hobby?",
    "Was there any moment you will smile back at in a breakout room telling your family about your day etc?",
    "What was one success you had yesterday?",
    "What is something you are still struggling with today?",
    "July 4th just passed... Did you shoot fireworks, watch a fireworks show, or do something else?",
    "What did you stock up on or do over the weekend to make this week easier?",
    "Pick a word to describe how you feel today? (ex: excited, nervous, sleepy, ready, confused, eager, etc.)",
    "What do you hope to accomplish today?",
    "What are your blockers (what might stop you)? If needed, can anyone help?",
    "What is one thing you figured out on your own during the workshop last Thursday/Friday?",
    "Shout outs! Did you learn something neat from someone else last week? If so, what and from whom?",
    "Pick a word to describe how you feel today? Do you remember what word you used on day 1?",
    "Is there any moment from HartCode you will smile back a few months from now? If so, what? (Ex: something in a breakout room? Telling your family about your day? Etc.)",
    "What's next? A vacation? Straight to the new role? Sleep?",
    "What is your favorite breakfast meal?",
    "What’s your caffeinated beverage of choice? Coffee? Tea? Cola - which one?",
    "What’s your favorite sandwich and why?",
    "What is your favorite ice cream flavor and ice cream topping?",
    "What's your favorite meal to cook and why?",
    "What food could you NOT live without?",
    "You are at the movie theater. What do you get -- popcorn, pickle, or M&Ms?",
    "What are you making for dinner tonight if you have to eat it every night for the next 7 days?",
    "Your company keeps snacks at work. What's the one snack you ask them to include?",
    "It's Taco Tuesday. What kind of taco are you eating?",
    "What is your favorite midnight snack?",
    "What’s the weirdest food you’ve ever eaten?",
    "If you had to pick only one of the following to eat every night for a year, which would you pick - American breakfast, Pho, Fajitas, Curry, or a burger?",
    "What was your favorite toy growing up?",
    "What was one of your favorite things to do as a kid?",
    "What is your cellphone wallpaper?",
    "What would you rather incorporate in your life: dog, cat, plant, or pet rock?",
    "Are you an early bird or night owl?",
    "What is your favorite time of the day and why?",
    "What’s your favorite tradition or holiday?",
    "What's your most used emoji?",
    "What’s your best scar story?",
    "What is the strangest habit you have?",
    "What is your hidden talent?",
    "What shoes do you have on right now?",
    "Did you have a locker in high school? Do you remember its number? And did you carry your books around in a backpack, stacked on a notebook, did you have no books?",
    "If you had a choice - would you play sports or play a musical instrument? Which instrument/sport and why?",
    "What is something you hate that other people love?",
    "What was the worst job you ever had?",
    "As a child, what did you want to be when you grew up?",
    "What current fact about your life would most impress your five-year-old self?",
    "What’s the most embarrassing fashion trend you used to rock?",
    "What was the last thing you bought at a store?",
    "What did you name your first car? Does your current car have a name? What is it?",
    "You have every TV show ever made available at your fingertips… what is the first thing you watch?",
    "If you and I were going to play card or board games this weekend, what would you want us to play?",
    "If I come to visit, what's the one local place you would take me to?",
    "What’s the last movie or TV show you watched or binge-watched?",
    "What movie do you think everyone should watch this weekend?",
    "What is one TV show you think everyone should watch?",
    "What kid's cartoon show do you still enjoy?",
    "What movie have you watched over and over?",
    "What song or album could you listen to on repeat?",
    "What is one place that you really want to visit that you haven't been to yet?",
    "What’s your favorite place of all the places you’ve traveled?",
    "What's one place you've always wanted to travel to?",
    "Who is your favorite villain?",
    "What’s the most out-of-character thing you’ve ever done?",
    "Have you ever completed anything on your “bucket list”?",
    "What's the most amazing thing you've seen in nature?",
    "How do you relieve stress and anxiety?",
    "What's your weirdest dream ever?",
    "Which do you prefer - ocean, lake, pool, or slip-n-slide?",
    "Are you a planner or are you spontaneous?",
    "Have you ever met someone famous in person? If so, who?",
    "Halloween - dress up and go out, hand out candy, turn off the lights and hide? What is your tradition? (Also…Best costume?)",
    "If you could learn one new personal skill, what would it be?",
    "If you had a million dollars, what would you buy first?",
    "If you could donate a million dollars to any charity, what cause would you choose?",
    "If you could build your dream house, what one cool quirky feature would you include?",
    "If you had to delete all but 3 apps from your smartphone, which ones would you keep?",
    "If you had your own late-night talk show, who do you invite as your first guest?",
    "If you were a superhero, what would your superhero name be?",
    "If the zombie apocalypse is coming, who are 3 people you want on your team?",
    "If you were a wrestler, what would be your entrance theme song?",
    "If you were stranded on a deserted island, would you rather be alone or be stuck there with your worst enemy? Which would you choose? Why?",
    "If aliens landed on earth tomorrow and offered to take you home with them, would you go?",
    "If you had a time machine, would you go back in time or into the future? Why?",
    "If you could get the answer to one 'question of life or history,' what would you want to know?",
    "If you are going to sail around the world, what will you name your boat?",
    "You are going to be transported into a TV or movie set -- what cast do you want to be a member of?",
    "If you become independently wealthy and don’t have to work, what will you do with your time?",
    "If you could live anywhere in the world for a year (without having to work), where would it be?",
    "You are going to compete on a reality or game show on TV. Which one would you choose and why?",
    "If you could hang out with any cartoon character, who would you choose and why?",
    "If you could switch lives with anyone for a day, who would it be?",
    "If you could bring back any fashion trend, what would it be?",
    "If you could choose any two famous people to have dinner with, who would they be?",
    "If you could be guaranteed one thing in life (besides money), what would it be?",
    "If you could add anyone to Mount Rushmore, who would it be and why?",
    "If you could compete in the summer Olympics, what sport would it be in?",
    "If you could teach a class on one thing, what would you teach?",
    "If you could eliminate one thing from your daily routine, what would it be and why?",
    "If you could have any superpower, what would it be?",
    "If your house was on fire and you could only grab three things, what would they be?",
    "If you had one opportunity to run a restaurant, what would you serve?",
    "If you could go back and re-live one high school moment, what would it be?",
    "Would you rather teach 1st graders or high schoolers? Why?",
    "Would you rather be a surgeon or an actor? Why?",
    "Would you rather be a superhero or the world’s best chef?",
    "Would you rather drive a Smart car, a Ford Mustang, a Jeep, or a crew cab pickup?",
    "Would you rather lose all of your money or all of your pictures?",
    "Would you rather visit a volcano or a rainforest?",
    "Would you rather go camping up in the Rocky Mountains, rent a beach house by the ocean in Hawaii, or spend a holiday in the city of San Francisco?",
    "Would you rather explore outer space or the bottom of the ocean?",
    "Would you rather climb Mt. Everest or swim the English Channel? Why?",
    "Would you rather water ski or snow ski? Why?",
    "Would you rather spend a summer in the Saharan desert or a winter in Antarctica?",
    "Would you rather backpack Europe or go on a (photo) African safari?",
    "Would you rather spend a vacation riding horses in Montana, seeing the sights of Las Vegas, or sailing around the Caribbean in a yacht?",
    "Would you rather spend a ride a rollercoaster or attend a jazz concert?",
    "Do the '6 word memoir' challenge as standup - tell a 'story' about yourself in only 6 words",
  ];

  // Randomly select a question
  const index = Math.floor(Math.random() * questions.length);
  document.getElementById("displayQuestion").innerHTML = questions[index];
}
