let students = [
  {
    name: "Brett Spokes",
    group: "App Dev Team",
    github: "https://github.com/BrettSpokes",
    linkedin: "https://www.linkedin.com/in/brett-spokes-8b758b29b/",
    email: "bspokes@appdev.yearup.org",
    nickname: "Any Key",
    imageUrl:
      "https://media.licdn.com/dms/image/D4E03AQHsvMOXofd4eg/profile-displayphoto-shrink_400_400/0/1701278215042?e=1722470400&v=beta&t=KVN23alt6xjixB3xlCNum6j26X4VRMmvCh6FdlsAFtM",
    gender: "male",
    devices: "Windows",
    xp: 0,
    currentlyWorkingOn: 81,
  },
  {
    name: "Alfi Ali",
    group: "App Dev Team",
    github: "https://github.com/ALFI-ALI",
    linkedin: "https://www.linkedin.com/in/alfi-ali-015506225/",
    email: "asamatar@appdev.yearup.org",
    nickname: "luffy",
    imageUrl:
      "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2022/12/luffy-with-his-straw-hat.jpg",
    gender: "male",
    devices: "Windows",
    xp: 0,
    currentlyWorkingOn: 44,
  },
  {
    name: "Dante 'Donny' Angerame",
    group: "App Dev Team",
    github: "https://github.com/DanteAngerame",
    linkedin: "https://www.linkedin.com/in/dante-angerame-739899192/",
    email: "dangerame@appdev.yearup.org",
    nickname: "The Woodchuck",
    imageUrl: "https://a-z-animals.com/media/2021/10/groundhog-1024x535.jpg",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: 32,
  },
  {
    name: "Guadalupe Argumedo Saucedo",
    group: "App Dev Team",
    github: "https://github.com/GuadalupeArgumedoSaucedo",
    linkedin:
      "https://www.linkedin.com/in/guadalupe-argumedo-saucedo-2b63b8303/",
    email: "gargumedosaucedo@appdev.yearup.org",
    nickname: "CodeLupe",
    imageUrl:
      "https://fakeimg.pl/600x400/7b37c4/fff700?text=Lupe+Argumedo&font=bebas",
    gender: "female",
    devices: "MAC",
    xp: 0,
    currentlyWorkingOn: 39,
  },
  {
    name: "Jaranesca Braker",
    group: "App Dev Team",
    github: "https://github.com/jaranesca",
    linkedin: "https://www.linkedin.com/in/jaranesca-braker-227810253/",
    email: "jbraker@appdev.yearup.org",
    nickname: "JSJ (JavaScript Jaranesca)",
    imageUrl: "https://fakeimg.pl/600x400/ffe44c/db29db?text=Jaranesca+Braker",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: 37,
  },
  {
    name: "Jesús Mimila",
    group: "App Dev Team",
    github: "https://github.com/JesusMimilaHurtado",
    linkedin: "https://www.linkedin.com/in/jesus-mimils-435b32274/",
    email: "jmimila@appdev.yearup.org",
    nickname: "JJ",
    imageUrl:
      "https://media.licdn.com/dms/image/D4E03AQFN9jSMTdbzDA/profile-displayphoto-shrink_400_400/0/1715103915979?e=1720656000&v=beta&t=5QnIvkUZJ9RX9KlBJbEPdKgv95eNmlrGAiDgvYd9k8A",
    devices: "MAC",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: 31,
    personalWebpage: "/jesus.html",
  },
  {
    name: "Kaaliyah Gray (Mac)",
    group: "App Dev Team",
    github: "https://github.com/KaaliyahGray",
    linkedin: "https://www.linkedin.com/in/kaaliyahgray-b03281237",
    email: "kgray@appdev.yearup.org",
    nickname: "leetheMrE",
    imageUrl:
      "https://media.licdn.com/dms/image/D5603AQEJtVL8lJLJpw/profile-displayphoto-shrink_400_400/0/1711738921148?e=1720656000&v=beta&t=VbkGPpHEA5sBDc8C96HVHrmvtBEJdt5TWW2bV-zuy18",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: 49,
    personalWebpage: "http://127.0.0.1:5500/kaaliyah.html",
  },
  {
    name: "Kadiatou Barry (Mac)",
    group: "App Dev Team",
    github: "https://github.com/kadylius/kadi-barry",
    linkedin: "https://www.linkedin.com/in/kadiatou-barry-a57bb8235/",
    email: "kbarry@appdev.yearup.org",
    nickname: "the connoisseur",
    imageUrl:
      "https://media.licdn.com/dms/image/C4E03AQELUNIRkpL2mQ/profile-displayphoto-shrink_400_400/0/1650085102341?e=1720656000&v=beta&t=mmwdGPGrsMGSixWu1_5aNj-9Cefa_n3CuCY3XSLXIr4",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: 39,
  },
  {
    name: "Kayla Hanifen (Mac)",
    group: "App Dev Team",
    github: "https://github.com/KaylaEHanifen",
    linkedin: "https://www.linkedin.com/in/kehanifen",
    email: "khanifen@appdev.yearup.org",
    nickname: "Agent K",
    imageUrl:
      "https://media.licdn.com/dms/image/D5603AQFHQ46apuKgbg/profile-displayphoto-shrink_400_400/0/1690255441190?e=1720656000&v=beta&t=vfjPfEJcHiS51C1tlT9DOG76R5n_PPJHoKirGzlHEuU",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: 36,
  },
  {
    name: "Leslie Alvarado (Mac)",
    group: "App Dev Team",
    github: "https://github.com/LeslieAlvarado1",
    linkedin: "https://www.linkedin.com/in/leslie-alvarado-connect/",
    email: "lalvarado@appdev.yearup.org",
    nickname: "The ScriptSiren",
    imageUrl:
      "https://media.licdn.com/dms/image/D5603AQHD4XcsiS9_7Q/profile-displayphoto-shrink_400_400/0/1714775792411?e=1720656000&v=beta&t=ti7w2I4510-NOGoVQqClRjXZ-XGsu673mSn6JDWZtRY",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: 48,
    personalWebpage: "/leslie.html",
  },
  {
    name: "Maximo Mayo",
    group: "App Dev Team",
    github: "https://github.com/MaximoMayo",
    linkedin: "https://www.linkedin.com/in/maximo-mayo-a2ba10252/",
    email: "mmayo@appdev.yearup.org",
    nickname: "reference error",
    imageUrl:
      "https://media.licdn.com/dms/image/D5635AQGJEoOx7l2_wg/profile-framedphoto-shrink_400_400/0/1668459290344?e=1715983200&v=beta&t=HUDrgjEalAYADICjvMh3t91vcTis3VBKVAUhR9FSgRk",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: 50,
  },
  {
    name: "Moncerrat Lua Salas",
    group: "App Dev Team",
    github: "https://github.com/MoncerratLuaSalas",
    linkedin: "https://www.linkedin.com/in/moncerrat-lua-salas/",
    email: "mluasalas@appdev.yearup.org",
    nickname: "Monce",
    imageUrl: "https://fakeimg.pl/600x400/fc8dd7/fad2e8?text=monce+so+swag",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: 45,
  },
  {
    name: "Niran Abdulqader",
    group: "App Dev Team",
    github: "https://github.com/NiranAbdulqader",
    linkedin: "https://www.linkedin.com/in/niran-abdulqader-/",
    personalWebpage: "Niran.html",
    email: "nabdulqader@appdev.yearup.org",
    nickname: "Techie Diva",
    imageUrl:
      "https://media.licdn.com/dms/image/C5603AQHCS9pI_VLNZQ/profile-displayphoto-shrink_800_800/0/1634626091348?e=1720656000&v=beta&t=GgD0cMSHbOwXtLXvKnhmQFg57BFgomFovZXPY28b14Q",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: 53,
  },
  {
    name: "Rene Banuelos",
    group: "App Dev Team",
    github: "https://github.com/ReneBA1999",
    linkedin: "https://www.linkedin.com/in/rene-banuelos-1881b52a2",
    email: "rbanuelos@appdev.yearup.org",
    nickname: "Cyber Samurai",
    imageUrl: "https://fakeimg.pl/400x400/120707/40b2eb?text=Rene+B",
    gender: "male",
    personalWebpage: "rene.html",
    xp: 0,
    currentlyWorkingOn: 30,
  },
  {
    name: "Uriel Delgado",
    group: "App Dev Team",
    github: "https://github.com/UrielDelgado",
    linkedin: "https://www.linkedin.com/in/uriel-delgado-3a49622bb/",
    email: "udelgado@appdev.yearup.org",
    nickname: "YaBoiUri",
    imageUrl:
      "https://fakeimg.pl/600x400/2ac458/c942c7?text=This+is+Uriel's+image.",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: 31,
  },
  {
    name: "Victor Castaneda",
    group: "App Dev Team",
    github: "https://github.com/Victor-Castaneda",
    linkedin: "https://www.linkedin.com/in/victor-castaneda/",
    email: "vcastaneda@appdev.yearup.org",
    nickname: "vic.exe",
    imageUrl:
      "https://media.licdn.com/dms/image/C4E03AQEzzEbWxGnohQ/profile-displayphoto-shrink_200_200/0/1559835011459?e=1721260800&v=beta&t=ERaw8MclKPqCGFt9YCF_jk7iuPpIgS9gZ5vP8Nypz3A",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: 33,
  },
  {
    name: "Remsey Mailjard",
    group: "IT Solutions Group",
    github: "https://github.com/RemseyMailjard",
    linkedin: "https://www.linkedin.com/in/remseymailjard/",
    email: "remsey@skills4-it.nl",
    nickname: "Mailjard the Magnificent",
    imageUrl: "https://www.remsey.nl/assets/images/remsey-mailjard.jpg",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: 0,
  },
  {
    name: "Daniel Solar",
    group: "App Dev Team",
    github: "https://github.com/1DanielSolar",
    linkedin: "https://www.linkedin.com/in/daniel-solar-464357300/",
    email: "dsolar@appdev.yearup.org",
    nickname: "Not Defined",
    imageUrl:
      "https://media.licdn.com/dms/image/D4D03AQHBE8cnwrNeZQ/profile-displayphoto-shrink_400_400/0/1715104324245?e=1720656000&v=beta&t=DIUF_40UXczsxkRaZB3Azjwsbg2TQgNuwk8da8-g9ek",
    gender: "male",
    xp: 0,
    currentlyWorkingOn: 33,
  },
  {
    name: "Andrea Ceballos",
    group: "App Dev Team",
    github: "https://github.com/iraryc",
    linkedin: "https://www.linkedin.com/in/andrea-irary/",
    email: "iraryc@gmail.com",
    nickname: "Kung Fu Koder",
    imageUrl:
      "https://media.licdn.com/dms/image/D5635AQEGBhG_qU_xJw/profile-framedphoto-shrink_400_400/0/1711041596221?e=1715983200&v=beta&t=3_LMe7iPRKe-cq6GHvXFEgnWp9Q_5HiY2XaDrFg_3EM",
    gender: "female",
    xp: 0,
    currentlyWorkingOn: 39,
  },
];
